export const designTokens = {
  colors: {
    surface: "#111317",
    surfaceDim: "#111317",
    surfaceBright: "#37393e",
    surfaceContainerLowest: "#0c0e12",
    surfaceContainerLow: "#1a1c20",
    surfaceContainer: "#1e2024",
    surfaceContainerHigh: "#282a2e",
    surfaceContainerHighest: "#333539",
    onSurface: "#e2e2e8",
    onSurfaceVariant: "#c1c6d6",
    outline: "#8b91a0",
    outlineVariant: "#414754",
    primary: "#acc7ff",
    onPrimary: "#002f67",
    primaryContainer: "#468fff",
    secondary: "#4edea3",
    secondaryFixed: "#6ffbbe",
    tertiary: "#ffb95f",
    tertiaryFixed: "#ffddb8",
    error: "#ffb4ab",
    errorContainer: "#93000a",
    onErrorContainer: "#ffdad6",
    background: "#111317",
  },
  spacing: {
    xs: "4px",
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "24px",
    containerPadding: "12px",
    gutter: "8px",
  },
  radii: {
    sm: "0.125rem",
    default: "0.25rem",
    md: "0.375rem",
    lg: "0.5rem",
    xl: "0.75rem",
    full: "9999px",
  },
  typography: {
    displaySm: {
      fontSize: "20px",
      fontWeight: 600,
      lineHeight: "28px",
      letterSpacing: "-0.01em",
    },
    headlineSm: {
      fontSize: "16px",
      fontWeight: 600,
      lineHeight: "24px",
      letterSpacing: "-0.01em",
    },
    titleMd: {
      fontSize: "14px",
      fontWeight: 600,
      lineHeight: "20px",
      letterSpacing: "0",
    },
    bodyMd: {
      fontSize: "13px",
      fontWeight: 400,
      lineHeight: "18px",
      letterSpacing: "0",
    },
    bodySm: {
      fontSize: "12px",
      fontWeight: 400,
      lineHeight: "16px",
      letterSpacing: "0",
    },
    labelMd: {
      fontSize: "11px",
      fontWeight: 500,
      lineHeight: "14px",
      letterSpacing: "0.02em",
    },
  },
} as const;

export type DesignTokens = typeof designTokens;
